src/Entity/Input.php
<?php

namespace App\Entity;

use App\Repository\InputRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InputRepository::class)
 */
class Input
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="inputs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="date")
     */
    private $input_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getInputDate(): ?\DateTimeInterface
    {
        return $this->input_date;
    }

    public function setInputDate(\DateTimeInterface $input_date): self
    {
        $this->input_date = $input_date;

        return $this;
    }
}

src/Form/InputType.php
<?php

namespace App\Form;

use App\Entity\Input;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InputType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('quantity')
            ->add('amount')
            ->add('input_date')
            ->add('product')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Input::class,
        ]);
    }
}

src/Controller/InputController.php
<?php

namespace App\Controller;

use App\Entity\Color;
use App\Entity\Input;
use App\Entity\Product;
use App\Entity\Size;
use App\Form\InputType;
use App\Repository\InputRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/input")
 */
class InputController extends AbstractController
{
    /**
     * @Route("/", name="input_index", methods={"GET"})
     */
    public function index(InputRepository $inputRepository): Response
    {
        return $this->render('input/index.html.twig', [
            'inputs' => $inputRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="input_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $input = new Input();
        $input->setInputDate(new \DateTime('today'));
        $form = $this->createFormBuilder($input)
            ->add('product', EntityType::class, [
                'class' => Product::class,
                'choice_label' => 'name'
            ])
            ->add('quantity', IntegerType::class)
            ->add('amount', NumberType::class)
            ->add('input_date', DateType::class)
            ->add('save', SubmitType::class, ['label' => 'Save'])
            ->getForm();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($input);
            $entityManager->flush();

            return $this->redirectToRoute('input_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('input/new.html.twig', [
            'input' => $input,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="input_show", methods={"GET"})
     */
    public function show(Input $input): Response
    {
        return $this->render('input/show.html.twig', [
            'input' => $input,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="input_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Input $input): Response
    {
        $form = $this->createFormBuilder($input)
            ->add('product', EntityType::class, [
                'class' => Product::class,
                'choice_label' => 'name'
            ])
            ->add('quantity', IntegerType::class)
            ->add('amount', NumberType::class)
            ->add('input_date', DateType::class)
            ->add('save', SubmitType::class, ['label' => 'Save'])
            ->getForm();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('input_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('input/edit.html.twig', [
            'input' => $input,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="input_delete", methods={"POST"})
     */
    public function delete(Request $request, Input $input): Response
    {
        if ($this->isCsrfTokenValid('delete'.$input->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($input);
            $entityManager->flush();
        }

        return $this->redirectToRoute('input_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/input/_delete_form.html.twig
<form method="post" action="{{ path('input_delete', {'id': input.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ input.id) }}">
    <button class="btn">Delete</button>
</form>

templates/input/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}

templates/input/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Input{% endblock %}

{% block body %}
    <h1>Edit Input</h1>

    {{ include('input/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('input_index') }}">back to list</a>

    {{ include('input/_delete_form.html.twig') }}
{% endblock %}

templates/input/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Input index{% endblock %}

{% block body %}
    <h1>Input index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Quantity</th>
                <th>Amount</th>
                <th>Input_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for input in inputs %}
            <tr>
                <td>{{ input.id }}</td>
                <td>{{ input.quantity }}</td>
                <td>{{ input.amount }}</td>
                <td>{{ input.inputDate ? input.inputDate|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('input_show', {'id': input.id}) }}">show</a>
                    <a href="{{ path('input_edit', {'id': input.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('input_new') }}">Create new</a>
{% endblock %}

templates/input/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Input{% endblock %}

{% block body %}
    <h1>Create new Input</h1>

    {{ include('input/_form.html.twig') }}

    <a href="{{ path('input_index') }}">back to list</a>
{% endblock %}

templates/input/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Input{% endblock %}

{% block body %}
    <h1>Input</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ input.id }}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{ input.quantity }}</td>
            </tr>
            <tr>
                <th>Amount</th>
                <td>{{ input.amount }}</td>
            </tr>
            <tr>
                <th>Input_date</th>
                <td>{{ input.inputDate ? input.inputDate|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('input_index') }}">back to list</a>

    <a href="{{ path('input_edit', {'id': input.id}) }}">edit</a>

    {{ include('input/_delete_form.html.twig') }}
{% endblock %}