src/Entity/Output.php
<?php

namespace App\Entity;

use App\Repository\OutputRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OutputRepository::class)
 */
class Output
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="outputs")
     */
    private $product;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="date")
     */
    private $output_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getOutputDate(): ?\DateTimeInterface
    {
        return $this->output_date;
    }

    public function setOutputDate(\DateTimeInterface $output_date): self
    {
        $this->output_date = $output_date;

        return $this;
    }
}

src/Form/OutputType.php
<?php

namespace App\Form;

use App\Entity\Output;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OutputType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('quantity')
            ->add('amount')
            ->add('output_date')
            ->add('product')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Output::class,
        ]);
    }
}

src/Controller/OutputController.php
<?php

namespace App\Controller;

use App\Entity\Output;
use App\Entity\Product;
use App\Form\OutputType;
use App\Repository\OutputRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/output")
 */
class OutputController extends AbstractController
{
    /**
     * @Route("/", name="output_index", methods={"GET"})
     */
    public function index(OutputRepository $outputRepository): Response
    {
        return $this->render('output/index.html.twig', [
            'outputs' => $outputRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="output_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $output = new Output();
        $output->setOutputDate(new \DateTime('today'));
        $form = $this->createFormBuilder($output)
            ->add('product', EntityType::class, [
                'class' => Product::class,
                'choice_label' => 'name'
            ])
            ->add('quantity', IntegerType::class)
            ->add('amount', NumberType::class)
            ->add('output_date', DateType::class)
            ->add('save', SubmitType::class, ['label' => 'Save'])
            ->getForm();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($output);
            $entityManager->flush();

            return $this->redirectToRoute('output_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('output/new.html.twig', [
            'output' => $output,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="output_show", methods={"GET"})
     */
    public function show(Output $output): Response
    {
        return $this->render('output/show.html.twig', [
            'output' => $output,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="output_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Output $output): Response
    {
        $form = $this->createFormBuilder($output)
            ->add('product', EntityType::class, [
                'class' => Product::class,
                'choice_label' => 'name'
            ])
            ->add('quantity', IntegerType::class)
            ->add('amount', NumberType::class)
            ->add('output_date', DateType::class)
            ->add('save', SubmitType::class, ['label' => 'Save'])
            ->getForm();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('output_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('output/edit.html.twig', [
            'output' => $output,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="output_delete", methods={"POST"})
     */
    public function delete(Request $request, Output $output): Response
    {
        if ($this->isCsrfTokenValid('delete'.$output->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($output);
            $entityManager->flush();
        }

        return $this->redirectToRoute('output_index', [], Response::HTTP_SEE_OTHER);
    }
    /**
     * @Route("/output/test", name="test_output", methods={"POST"})
     */
    public function test(Request $request): JsonResponse
    {
        $data = json_decode($request->getContent(), true);

        return new JsonResponse($data, Response::HTTP_CREATED);
    }
}

templates/output/_delete_form.html.twig
<form method="post" action="{{ path('output_delete', {'id': output.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ output.id) }}">
    <button class="btn">Delete</button>
</form>

templates/output/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}

templates/output/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Output{% endblock %}

{% block body %}
    <h1>Edit Output</h1>

    {{ include('output/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('output_index') }}">back to list</a>

    {{ include('output/_delete_form.html.twig') }}
{% endblock %}

templates/output/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Output index{% endblock %}

{% block body %}
    <h1>Output index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Quantity</th>
                <th>Amount</th>
                <th>Output_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for output in outputs %}
            <tr>
                <td>{{ output.id }}</td>
                <td>{{ output.quantity }}</td>
                <td>{{ output.amount }}</td>
                <td>{{ output.outputDate ? output.outputDate|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('output_show', {'id': output.id}) }}">show</a>
                    <a href="{{ path('output_edit', {'id': output.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('output_new') }}">Create new</a>
{% endblock %}

templates/output/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Output{% endblock %}

{% block body %}
    <h1>Create new Output</h1>

    {{ include('output/_form.html.twig') }}

    <a href="{{ path('output_index') }}">back to list</a>
{% endblock %}

templates/output/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Output{% endblock %}

{% block body %}
    <h1>Output</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ output.id }}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{ output.quantity }}</td>
            </tr>
            <tr>
                <th>Amount</th>
                <td>{{ output.amount }}</td>
            </tr>
            <tr>
                <th>Output_date</th>
                <td>{{ output.outputDate ? output.outputDate|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('output_index') }}">back to list</a>

    <a href="{{ path('output_edit', {'id': output.id}) }}">edit</a>

    {{ include('output/_delete_form.html.twig') }}
{% endblock %}